services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: ["python", "-m", "app.worker"]
    depends_on:
      - redis
